Test check on existing file

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -65,12 +65,26 @@ jobs:
           submodules: recursive
           ref: ${{ github.ref_name }}
 
+      - name: Check version
+        run: |
+          set +e
+          # Extract version number
+          VERSION=$(awk '/"version":/ { print substr($2, 2, length($2)-3); exit }' app/package.json)
+
+          TAG_VERSION=${{ github.ref_name }}
+          if [ $VERSION -ne $TAG_VERSION ]; then
+            echo "Tag version is not correct. Tag version: $TAG_VERSION version from package.json: $VERSION"
+            EC=0
+            exit 1
+          fi
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
       - name: build ci image
         if: ${{ env.EC == 254 }}
         uses: docker/build-push-action@v6
         with:
           push: true
-          tags: "192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/desktop-wallet-ci:test"
+          tags: "192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/desktop-wallet-ci:${{ env.VERSION }}-test"
           context: '.'
           file: 'scripts/desktop-wallet-ci.Dockerfile'
           build-args: |
@@ -109,30 +123,28 @@ jobs:
       - name: check if executable exist
         run: |
           set +e
-          # Extract version number
-          VERSION=$(awk '/"version":/ { print substr($2, 2, length($2)-3); exit }' app/package.json)
           TARGET_NET=${{env.TARGET_NET}}
 
           # Prepare filenames
           if [ $TARGET_NET = "mainnet" ]; then
-             FILENAME_DEB="concordium-desktop-wallet-${VERSION}.deb"
-             FILENAME_RPM="concordium-desktop-wallet-${VERSION}.rpm"
-             FILENAME_APPIMAGE="concordium-desktop-wallet-${VERSION}.AppImage"
-             FILENAME="concordium-desktop-wallet-${VERSION}"
+             FILENAME_DEB="concordium-desktop-wallet-${{ env.VERSION }}.deb"
+             FILENAME_RPM="concordium-desktop-wallet-${{ env.VERSION }}.rpm"
+             FILENAME_APPIMAGE="concordium-desktop-wallet-${{ env.VERSION }}.AppImage"
+             FILENAME="concordium-desktop-wallet-${{ env.VERSION }}"
           else
-             FILENAME_DEB="concordium-desktop-wallet-${TARGET_NET}-${VERSION}.deb"
-             FILENAME_RPM="concordium-desktop-wallet-${TARGET_NET}-${VERSION}.rpm"
-             FILENAME_APPIMAGE="concordium-desktop-wallet-${TARGET_NET}-${VERSION}.AppImage"
-             FILENAME="concordium-desktop-wallet-${TARGET_NET}-${VERSION}"
+             FILENAME_DEB="concordium-desktop-wallet-${TARGET_NET}-${{ env.VERSION }}.deb"
+             FILENAME_RPM="concordium-desktop-wallet-${TARGET_NET}-${{ env.VERSION }}.rpm"
+             FILENAME_APPIMAGE="concordium-desktop-wallet-${TARGET_NET}-${{ env.VERSION }}.AppImage"
+             FILENAME="concordium-desktop-wallet-${TARGET_NET}-${{ env.VERSION }}"
           fi
 
           FILENAME_LATEST_LINUX="latest-linux.yml"
 
-          OUT_FILENAME_DEB="${VERSION}/${TARGET_NET}/${FILENAME_DEB}"
-          OUT_FILENAME_RPM="${VERSION}/${TARGET_NET}/${FILENAME_RPM}"
-          OUT_FILENAME_APPIMAGE="${VERSION}/${TARGET_NET}/${FILENAME_APPIMAGE}"
-          OUT_FILENAME="${VERSION}/${TARGET_NET}/${FILENAME}"
-          OUT_LATEST_LINUX="${VERSION}/${TARGET_NET}/latest-linux.yml"
+          OUT_FILENAME_DEB="${{ env.VERSION }}/${TARGET_NET}/${FILENAME_DEB}"
+          OUT_FILENAME_RPM="${{ env.VERSION }}/${TARGET_NET}/${FILENAME_RPM}"
+          OUT_FILENAME_APPIMAGE="${{ env.VERSION }}/${TARGET_NET}/${FILENAME_APPIMAGE}"
+          OUT_FILENAME="${{ env.VERSION }}/${TARGET_NET}/${FILENAME}"
+          OUT_LATEST_LINUX="${{ env.VERSION }}/${TARGET_NET}/latest-linux.yml"
           aws s3 ls ${{env.S3_BUCKET}}/${OUT_FILENAME}.deb
           EC=$?
           if [ EC -eq 0 ]; then
@@ -171,87 +183,86 @@ jobs:
           aws s3 cp "release/${{ env.FILENAME }}.AppImage" "${{env.S3_BUCKET}}/test/${{ env.OUT_FILENAME }}.rpm" --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
           aws s3 cp "release/latest-linux.yml" "${{env.S3_BUCKET}}/test/${{ env.OUT_YML_FILENAME }}" --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
 
-#  #using windows-2019 to be able to use visual studio 2019, newer versions do not support older versions of node
-#  release-desktop-wallet-windows:
-#    runs-on: windows-2019
-#    environment: release
-#    needs: login-aws
-#    steps:
-#      - name: aws creds
-#        uses: aws-actions/configure-aws-credentials@v4
-#        id: creds
-#        with:
-#          aws-region: "eu-west-1"
-#          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
-#          role-session-name: ReleaseDesktopWalletSession
-#          
-#      - name: Checkout repository
-#        uses: actions/checkout@v4
-#        with:
-#          submodules: recursive
-#          ref: v1.7.4
-#      - name: install dependencies
-#        uses: jetli/wasm-pack-action@v0.4.0
-#        with:
-#          version: 'v0.9.1'
-#
-#      - name: install node
-#        uses: actions/setup-node@v4
-#        with:
-#          node-version: 14.16.0
-#
-#      - name: Check if file exists
-#        shell: bash
-#        run: |
-#          set +e
-#          # Extract version number
-#          VERSION=$(awk '/"version":/ { print substr($2, 2, length($2)-3); exit }' app/package.json)
-#          TARGET_NET=${{env.TARGET_NET}}
-#  
-#          if [ $TARGET_NET = "mainnet" ]; then
-#              FILENAME_EXE="concordium-desktop-wallet-${VERSION}.exe"
-#          else
-#              FILENAME_EXE="concordium-desktop-wallet-${TARGET_NET}-${VERSION}.exe"
-#          fi
-#          OUT_YML="${VERSION}/${TARGET_NET}/latest.yml"
-#          OUT_FILENAME_EXE="${VERSION}/${TARGET_NET}/${FILENAME_EXE}"
-#          aws s3 ls ${{ env.S3_BUCKET }}/$OUT_FILENAME_EXE
-#          EC=$?
-#          echo $EC
-#          if [ $EC -eq 0 ]; then
-#            echo "$OUT_OBJECT already exist"
-#          elif [ $EC -ne 1 ]; then
-#            echo "Error: $EC"
-#          fi
-#          echo "OUT_EXE=$OUT_FILENAME_EXE" >> $GITHUB_ENV
-#          echo "FILENAME_EXE=$FILENAME_EXE" >> $GITHUB_ENV
-#          echo "OUT_YML=$OUT_YML" >> $GITHUB_ENV
-#          echo "EXIT_CODE=$EC" >> $GITHUB_ENV
-#          
-#          
-#      - name: Build and push desktop wallet
-#        if: ${{ env.EXIT_CODE == 1 }}
-#        shell: bash
-#        run: |
-#          TARGET_NET=${{env.TARGET_NET}}
-#
-#          # Print system info
-#          node --version
-#          npm --version
-#          yarn --version
-#          python --version
-#          rustup show
-#          wasm-pack --version
-#
-#          # Install dependencies
-#          yarn --network-timeout 1000000
-#
-#          # Build
-#          yarn package-win-no-sign
-#
-#          ls release
-#
-#          # Push
-#          aws s3 cp "release/latest.yml" ${{ env.S3_BUCKET }}/${{ env.OUT_YML }} --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
-#          aws s3 cp "release/${{ env.FILENAME_EXE}}" ${{ env.S3_BUCKET }}/${{ env.OUT_EXE }} --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
+  #using windows-2019 to be able to use visual studio 2019, newer versions do not support older versions of node
+  release-desktop-wallet-windows:
+    runs-on: windows-2019
+    environment: release
+    needs: login-aws
+    steps:
+      - name: aws creds
+        uses: aws-actions/configure-aws-credentials@v4
+        id: creds
+        with:
+          aws-region: "eu-west-1"
+          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
+          role-session-name: ReleaseDesktopWalletSession
+          
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+          ref: ${{ github.ref_name }}
+      - name: install dependencies
+        uses: jetli/wasm-pack-action@v0.4.0
+        with:
+          version: 'v0.9.1'
+
+      - name: install node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 14.16.0
+
+      - name: Check if file exists
+        shell: bash
+        run: |
+          set +e
+          TARGET_NET=${{env.TARGET_NET}}
+
+  
+          if [ $TARGET_NET = "mainnet" ]; then
+              FILENAME_EXE="concordium-desktop-wallet-${{ env.VERSION }}.exe"
+          else
+              FILENAME_EXE="concordium-desktop-wallet-${TARGET_NET}-${{ env.VERSION }}.exe"
+          fi
+          OUT_YML="${{ env.VERSION }}/${TARGET_NET}/latest.yml"
+          OUT_FILENAME_EXE="${{ env.VERSION }}/${TARGET_NET}/${FILENAME_EXE}"
+          aws s3 ls ${{ env.S3_BUCKET }}/$OUT_FILENAME_EXE
+          EC=$?
+          echo $EC
+          if [ $EC -eq 0 ]; then
+            echo "$OUT_OBJECT already exist"
+          elif [ $EC -ne 1 ]; then
+            echo "Error: $EC"
+          fi
+          echo "OUT_EXE=$OUT_FILENAME_EXE" >> $GITHUB_ENV
+          echo "FILENAME_EXE=$FILENAME_EXE" >> $GITHUB_ENV
+          echo "OUT_YML=$OUT_YML" >> $GITHUB_ENV
+          echo "EXIT_CODE=$EC" >> $GITHUB_ENV
+          
+          
+      - name: Build and push desktop wallet
+        if: ${{ env.EXIT_CODE == 1 }}
+        shell: bash
+        run: |
+          TARGET_NET=${{env.TARGET_NET}}
+
+          # Print system info
+          node --version
+          npm --version
+          yarn --version
+          python --version
+          rustup show
+          wasm-pack --version
+
+          # Install dependencies
+          yarn --network-timeout 1000000
+
+          # Build
+          yarn package-win-no-sign
+
+          ls release
+
+          # Push
+          aws s3 cp "release/latest.yml" ${{ env.S3_BUCKET }}/test/${{ env.OUT_YML }} --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
+          aws s3 cp "release/${{ env.FILENAME_EXE}}" ${{ env.S3_BUCKET }}/test/${{ env.OUT_EXE }} --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
     
